language: java
notifications:
  email: false
  slack:
    secure: TrFpL2wGDdlsDhL3kEy85SjZs9WAU0iJd9w9bs6AVlEeF8eQYgOKAqEPyaiGisUkvxxokznpLAUKXR0RCBthJJzYMjR8QKzCPTgiTZ21HvkA4Bn0sYXt7tx2ZqBTlHiwNNvdFSPx4RXDY7A7S9OkYJl+WjAILnOtG+HxsfGNGLR6O1S350iVYwMVTMnXWWg2gfDXu97x59PYW1r1NQ1EerxbcOsSx6M32e4btnuLaIHDlYRsK7yaY3OCOe1h/tnBve3Nolco6PBlcVgBLLhFU6fWwY/F+R9N+Aazj0kDAuQi+WixKf2PfVMTlMdjHFX1ZpscRzEY0UNjqyktVK2pLd+aUjUoRMCS0Xm+IPY2Z/S1MoHuZjEPsqBpIg/E6ZYizCRMTV6Ao0iET96EhlHqnR/2+XrwOvun7zOVK+Iu719xZLwBw6Ghyy0Y6i+8h6zzneHxxq/tz5Ggl/da0uPhEwQ34soGYgTSMhHWP9LLQeCkz5r1P+GEumBiunp8PpIG06twdpkMe1IW+ROufDN2YqlypFmJos0cq+5KdhzQmDGjG89iJ9U9Wk6bAHJV5WnIg9jXHhzYSaRyYfOvYqm6k+ThQBW3evDCOegRwm+3dmhyWU0rrbxCcOIZm1AllP00tOR5TYcQpDdDqkG47m0DZhw3BQsy5GBOUDHAwpODohA=
jdk:
- oraclejdk8
install: echo 'Run Maven Tests'
script:
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install --settings sonar:sonar .travis/settings.xml -Dmaven.javadoc.skip=true -B -V
- mvn clean install --settings .travis/settings.xml -Dmaven.javadoc.skip=true -B -V
after_success: mvn deploy --settings .travis/settings.xml -DskipTests -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: PCFOUFACtFGCDyNabdbfhqAaXCTCppOcuNZGWWk+sQcPyqR0QwUvVboc7hAdtCl4rqHoHBddjsPn0V84i3ocox0EdvotbgwvrgM9OS8vrbSfOBKQzhjv6UKEpq9LdbeOZqUxf09n0de1vtm3RqaS8BJdhHdKlXQQ92cNDUznc3+T/tezA+AKu3z0nKrcvwG0PslBRmzFwi++nTf1TefGg3v6oOCa1lsXXMM5KThVE6NDF+DUwa9IjBxEWzwoqMEnOoiCAD48yhPvajdFaZaE1jRxmJoThQowjZSV0/Wt860xv8JLlLKjHlGVUDc2yU+hQJRtqlI5N+68evUCb5eCIOhLgwIIyHnQbE6TjE4y26zaiSANYwLaEgyOxVtukSQJ6yvdEGVtvNkPXI4dYuAJbJ+rKhywg0x0mzKGeiNJny1Y1B8rs3xnX8W4zFCaNzbU/0/k5CGYAafsB3oaAYdEff72v7i8qsufKJY8lDduRBoNViEfhYXJuFIS2jiLRoPgB/q63IFJXxEOXZEsr+74RIxUQok0hrP+Qelq5qjz2d0KiixJj9t8SNitN/0WC6//AFdGmXxh67u037U+PYDYbOBNtd9AXf6ybokft5h7U+RFrbJj77ODi0utkub/SgTCpX6pcZPGCllkSvPH4LzJxcri3oVmXqDDyzfsq/Lntqk=
  - secure: mJezXNjuDRjHKze005SHebveTfcgGgc/wSLzs+qL15ISNE1hovphseTSJIA6oRHXq/TR854gqcthvGVtyiF/0nTdaamfBBpwFuAQ2w7+JMN/15k+1BmtmQ7ELDypSVrtYEe7+SasxXZ/f1BQj0egWvSs+EN4IuZ/LjI94H77lq/sN++VXmE4DGPv5nZmkj6MCBPEN2h6zxfaPy+v4L1SIuNvYHgjFaj1BS7UMFmR6dTZqNf+4msKUpo20Np1Sv8tWO5pnxSl6CX2S6cTwcSmcPTy8jEVDYxp1oUqwVWwrNsYT3TW11Kf/3aUz+NzSZoxh9SNY7axh+Ok97u2ZxRmIk1fpDaNYScA7KHX5/85zN/OQ1FH6lk9Z8ingpEqR5emGiq/hqs7SfMW3VG4EoKElyT3OsM1FDAp802fPni4Ug5TGW2vFQpW/h9edpGM9NvaqBg9ZjL8cISM36QMPXFcFBBvMZx1vtqzXoEC/+WbLi5g1maY4L63y8iw3sWEAUMxgXw3H/osI4/5/I0PZvnQEhkNe+cteLFbGsMlRVUtbaNzgUH5z36r6Yo4GOmVcxkSPLL79huYa4nJncxXdjVI+g3y0NFoqC+yUqMcM5NtIhknim31mI3L+OSKI1DM2OcwkHc575NzsTjsYtw9BliJ8RQEBdDm93SmfCnuiKiKD8E=
